config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :businesses do
    member do
      get :table_statistics
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :channels
  resources :goals do 
    member do
      get :scoreboard_summary
    end

    collection do
      get :form_error_page
    end
  end
  resources :products
  resources :weekly_data_entries do
    collection do
      get :form_error_page
    end
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  layout "dashboard_layout"
  before_action :set_business, only: %i[ show edit update destroy table_statistics]

  # GET /businesses or /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1 or /businesses/1.json
  def show
    @channel = Channel.new
    @goal = Goal.new
    @product = Product.new
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses or /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to business_url(@business), notice: "Business was successfully created." }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1 or /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to business_url(@business), notice: "Business was successfully updated." }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1 or /businesses/1.json
  def destroy
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url, notice: "Business was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def table_statistics
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def business_params
      params.require(:business).permit(:name, :num_of_employees, :industry_id, :user_id)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business.html.erb
<div class="col-md-2 card py-4 text-center mx-auto normal-fonts" id="<%= dom_id business %>">
  <p>
    <strong>Name:</strong>
    <%= business.name %>
  </p>

  <p>
    <strong>Num of employees:</strong>
    <%= business.num_of_employees %>
  </p>

  <p>
    <strong>Industry:</strong>
    <%= business.industry.name %>
  </p>

  <div class="text-center">
    <%= link_to "View", business, class: "btn btn-primary" %>
  </div>

</div>

app/views/businesses/_business_show_card.html.erb
<p>
  <strong>Name:</strong>
  <%= business.name %>
</p>
<p>
  <strong>Num of employees:</strong>
  <%= business.num_of_employees %>
</p>
<p>
  <strong>Industry:</strong>
  <%= business.industry.name %>
</p>

app/views/businesses/_form.html.erb
<%= form_with(model: business) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% business.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <%= form.label :name, "Business Name" %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="col-md-6">
      <%= form.label :num_of_employees, "Number Of Employees" %>
      <%= form.text_field :num_of_employees, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= form.label :industry_id, style: "display: block" %>
      <%= form.collection_select :industry_id, Industry.all.order(:name), :id, :name, prompt: true, class: "form-control", required: true %>
    </div>

    <div>
      <%= form.text_field :user_id, value: current_user.id, style: "display: none" %>
    </div>
  </div>

  <div>
    <%= form.submit "Create Business", class: "btn btn-success my-3" %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render "form", business: @business %>

<br>

<div>
  <%= link_to "Show this business", @business %> |
  <%= link_to "Back to businesses", businesses_path %>
</div>

app/views/businesses/index.html.erb
<div class="container-fluid">
  <h4 class="text-center my-5">Businesses</h4>
  <% if current_user.businesses.size < 1 %>
    <div class="text-center normal-fonts">
      <p>Please Create a Business</p>
      <%= link_to "New business", new_business_path, class: "btn btn-primary" %>
    </div>
  <% end %>
  <div class="row">
    <div id="businesses">
      <% @businesses.each do |business| %>
        <%= render business %>
      <% end %>
    </div>
  </div>
</div>

app/views/businesses/new.html.erb
<div class="container-fluid bg-light p-5" style="height: 100vh">
  <h2 class="heading-fonts text-center my-5">Setup Your Business</h2>
  <div class="row">
    <div class="col-md-7 mx-auto">
      <%= render "form", business: @business %>
    </div>
  </div>
</div>

app/views/businesses/show.html.erb
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Business Goals</h1>
  <div class="row">
    <div class="col-lg-3">
      <!-- Business Information -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold" style="color: black">
            <i class="fas fa-building"></i>
            Business Information
          </h6>
        </div>
        <div class="card-body">
          <%= render partial: "businesses/business_show_card", locals: { business: @business } %>
          <!-- Show Business Data (Default) -->
        </div>
      </div>
      <!-- Add Channels & Products -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold" style="color: black">
            <i class="bi bi-1-circle"></i>
            Products & Sevices
          </h6>
        </div>
        <div class="card-body">
          <% @business.products.each do |product| %>
            <div class="row">
              <div class="col-md-8">
                <%= render partial: "products/product", locals: { product: product } %>
              </div>
              <div class="col-md-2">
                <%= render partial: "products/modal", locals: { product: product, id_suffix: product.id, form_type: "Edit" } %>
              </div>
              <div class="col-md-2">
                <%= link_to product_path(product), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "general-delete-link" do %>
                  <i class="bi bi-x-circle"></i>
                <% end %>
              </div>
            </div>
          <% end %>
          <%= render partial: "products/modal", locals: { product: @product, id_suffix: 0, form_type: "Create" } %>
        </div>
      </div>
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold" style="color: black">
            Business Channels
          </h6>
        </div>
        <div class="card-body">
          <div class="row">
            <% @business.channels.each do |channel| %>
              <div class="col-md-8">
                <%= render partial: "channels/channel", locals: { channel: channel} %>
              </div>
              <div class="col-md-2">
                <%= render partial: "channels/modal", locals: { channel: channel, id_suffix: channel.id, form_type: "edit", btn_text: "Update" } %>
              </div>
              <div class="col-md-2">
                <%= link_to channel_path(channel), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "general-delete-link" do %>
                  <i class="bi bi-x-circle"></i>
                <% end %>
              </div>
            <% end %>
          </div>
          <%= render partial: "channels/modal", locals: { channel: @channel, id_suffix: 0, form_type: "create", btn_text: "Create" } %>
        </div>
      </div>
    </div>
    <!-- Setup Business Goals -->
    <div class="col-lg-9">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold" style="color: black">
            Setup Goals
          </h6>
        </div>
        <div class="card-body text-white" style="background-color:#047d57">
          <p>
            Create a business goal for each
            quarter of the year.
          </p>
          <%= render partial: "goals/modal", locals: { form_type: "create", id_suffix: 0, goal: @goal, btn_text: "Add Goal" } %>
          <div class="row my-3">
            <% @business.goals.each do |goal| %>
              <%= render partial: "goals/goal", locals: { goal: goal } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/table_statistics.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold" style="color: black;">Leads Performance</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Time</th>
            <th>Projected Leads</th>
            <th>Actual Leads</th>
            <th>Surplus / Deficit</th>
            <th>Abandoned Leads</th>
            <th>Conversion Rate</th>
            <th>Budget</th>
            <th>Revenue</th>
          </tr>
        </thead>
        <tbody>
          <% @business.goals.each do |goal| %>
            <tr>
              <th><%= link_to goal.unique_code, scoreboard_summary_goal_path(goal), class: "general-view-link" %> </th>
              <td><%= goal.projected_leads %></td>
              <td><%= goal.actual_leads %></td>
              <td><%= goal.lead_difference %></td>
              <td><%= goal.abandoned_leads %></td>
              <td><%= goal.conversion_rate.round(2) %> %</td>
              <td> $ <%= goal.budget %></td>
              <td> $ <%= goal.revenue %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>