config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :businesses do
    member do
      get :table_statistics
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :channels
  resources :goals do 
    member do
      get :scoreboard_summary
    end

    collection do
      get :form_error_page
    end
  end
  resources :products
  resources :weekly_data_entries do
    collection do
      get :form_error_page
    end
  end
end

app/models/weekly_data_entry.rb
class WeeklyDataEntry < ApplicationRecord
  belongs_to :goal
  belongs_to :business
  belongs_to :user

  before_save :set_leads_per_week, :set_conversion_rate
  after_save :update_related_goal_attributes

  validate :product_channel_leads_equality, :contacted_less_than_total_leads

  scope :business_yearly_data, -> (business_id, date) { where("business_id = #{business_id} AND date >= '#{date.beginning_of_year}' AND date <= '#{date.end_of_year}'") }

  def product_channel_leads_equality
    errors.add(:channel_leads_and_product_leads, "Product Leads should equal Channel leads") unless sum_weekly_channel_leads == sum_weekly_product_leads
  end

  def contacted_less_than_total_leads
    errors.add(:contacted_leads, "Can not be greater than total leads") if contacted_leads > sum_weekly_channel_leads
  end

  def parse_channel_leads(params)
    leads_per_channel = []
    business.channels.each do |channel|
      leads_per_channel << { "#{channel.name}" => params["#{channel.name}"] } if goal.channel_arr.include?(channel.name)
    end

    self.channel_leads_per_week = leads_per_channel
  end

  def sum_weekly_channel_leads
    parsed_channels = self.channel_leads_per_week.map{ |c| eval(c) }
    parsed_channels.map{ |c| c.values.first.to_i }.sum
  end

  def sum_weekly_product_leads
    parsed_products = self.product_leads_per_week.map{ |c| eval(c) }
    parsed_products.map{ |c| c.values.first.to_i }.sum
  end

  def set_leads_per_week
    self.leads_per_week = sum_weekly_channel_leads
  end

  def parse_product_leads(params)
    leads_per_product = []
    business.products.each do |product|
      leads_per_product << { "#{product.name}" => params["#{product.name}"] } if goal.product_arr.include?(product.name)
    end

    self.product_leads_per_week = leads_per_product
  end

  def parse_leads(params)
    parse_channel_leads(params)
    parse_product_leads(params)
  end

  def calc_conversion_rate
    (paid_customers.to_f / sum_weekly_channel_leads.to_f) * 100
  end

  def set_conversion_rate
    self.conversion_rate = calc_conversion_rate
  end

  def channel_leads_array_of_hashes
    channel_leads_per_week.map{ |channel| eval(channel) }
  end

  def product_leads_array_of_hashes
    product_leads_per_week.map{ |product| eval(product) }
  end

  def channel_leads_hash # merge channel_leads_per_week into a big hash
    channel_leads_array_of_hashes.reduce(Hash.new) { |main_hash, other_hash| main_hash.merge(other_hash) }
  end

  def product_leads_hash # merge product_leads_per_week into a big hash
    product_leads_array_of_hashes.reduce(Hash.new) { |main_hash, other_hash| main_hash.merge(other_hash) }
  end

  def self.goal_ids(data_entries)
    data_entries.map(&:goal_id).uniq
  end

  def self.yearly_actual_leads(data_entries)
    Goal.where(id: self.goal_ids(data_entries)).map(&:actual_leads).sum
  end

  def self.yearly_contacted_leads(data_entries)
    data_entries.map(&:contacted_leads).sum
  end

  def self.yearly_projected_leads(data_entries)
    Goal.where(id: self.goal_ids(data_entries)).map(&:projected_leads).sum
  end

  def self.yearly_lead_difference(data_entries)
    self.yearly_actual_leads(data_entries) - self.yearly_projected_leads(data_entries)
  end

  def self.yearly_lead_progress(data_entries)
    progress = (self.yearly_actual_leads(data_entries).to_f / self.yearly_projected_leads(data_entries).to_f) * 100
    progress.round
  end

  def self.yearly_conversion_rate(data_entries)
    data_entries.map(&:conversion_rate).sum / data_entries.count
  end

  def self.yearly_data_channel_initialize_hash(data_entries)
    channel_hash = Hash.new
    data_entry = data_entries.first
    date_to_query = data_entry.date
    @business_id = data_entry.business_id
    goals = Goal.where("business_id = #{@business_id} AND created_at >= '#{date_to_query.beginning_of_year}' AND created_at <= '#{date_to_query.end_of_year}'")
    goals.each do |goal|
      goal.channels.split("-#-").map(&:strip).each do |channel|
        channel_hash[channel] = 0
      end
    end

    channel_hash
  end

  def self.yearly_parse_channels_chart_data(data_entries, in_percentage: false)
    data_set = self.yearly_data_channel_initialize_hash(data_entries)
    data_entries.each do |data|
      data.channel_leads_hash.each do |key, value|
        data_set[key] += value.to_i if data_set[key].present?
      end
    end

    in_percentage ? self.data_to_percentage(data_set) : data_set
  end

  def self.yearly_data_product_initialize_hash(data_entries)
    product_hash = Hash.new
    data_entry = data_entries.first
    date_to_query = data_entry.date
    @business_id = data_entry.business_id 
    goals = Goal.where("business_id = #{@business_id} AND created_at >= '#{date_to_query.beginning_of_year}' AND created_at <= '#{date_to_query.end_of_year}'")
    goals.each do |goal|
      goal.products.split("-#-").map(&:strip).each do |product|
        product_hash[product] = 0
      end
    end

    product_hash
  end

  def self.yearly_parse_products_chart_data(data_entries, in_percentage: false)
    data_set = self.yearly_data_product_initialize_hash(data_entries)
    data_entries.each do |data|
      data.product_leads_hash.each do |key, value|
        data_set[key] += value.to_i if data_set[key].present?
      end
    end

    in_percentage ? self.data_to_percentage(data_set) : data_set
  end

  def self.data_to_percentage(data_set)
    sum = data_set.values.sum.to_f
    data_set.each do |key, value|
      data_set[key] = ((value.to_f/sum) * 100).round(2)
    end

    data_set
  end

  def self.yearly_abandoned_leads(data_entries)
    self.yearly_actual_leads(data_entries) - self.yearly_contacted_leads(data_entries)
  end

  def self.parse_yearly_contacted_vs_abandoned_leads(data_entries, in_percentage: false)
    if in_percentage
      sum = (self.yearly_contacted_leads(data_entries) + self.yearly_abandoned_leads(data_entries)).to_f
      contacted_leads_percent = (self.yearly_contacted_leads(data_entries).to_f / sum) * 100
      abandoned_leads_percent = (self.yearly_abandoned_leads(data_entries).to_f / sum) * 100
      { "Contacted Leads" => contacted_leads_percent.round(2), "Abondoned Leads" => abandoned_leads_percent.round(2)}
    else
      { "Contacted Leads" => self.yearly_contacted_leads(data_entries), "Abondoned Leads" => self.yearly_abandoned_leads(data_entries) }
    end
  end

  private 

  def update_related_goal_attributes
    goal.update_related_fields_based_on_weekly_data_changes
  end
end

app/controllers/weekly_data_entries_controller.rb
class WeeklyDataEntriesController < ApplicationController
  before_action :set_weekly_data_entry, only: [:form_error_page, :update, :destroy]

  def create
    @goal = Goal.find_by(id: params[:weekly_data_entry][:goal_id])
    @weekly_data_entry = WeeklyDataEntry.new(weekly_data_entry_params)
    @weekly_data_entry.parse_leads(params)
    respond_to do |format|
      if @weekly_data_entry.save
        format.html { redirect_to @goal, notice: "Data Entry was successfully Added" }
      else
        format.html { render "form_error_page", alert: "Data Entry could not be created", status: :unprocessable_entity }
      end
    end
  end

  def update
    @goal = Goal.find_by(id: params[:weekly_data_entry][:goal_id])
    @weekly_data_entry.parse_leads(params)
    respond_to do |format|
      if @weekly_data_entry.update(weekly_data_entry_params)
        format.html { redirect_to @goal, notice: "Data Entry was successfully Updated" }
      else
        format.html { render "form_error_page", alert: "Data Entry could not be Updated", status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @goal = @weekly_data_entry.goal
    @weekly_data_entry.destroy
    flash[:alert] = "Data Entry was successfully deleted"
    redirect_to @goal
  end

  def form_error_page
  end

  private 

  def set_weekly_data_entry
    @weekly_data_entry = WeeklyDataEntry.find_by(id: params[:id])
  end

  def weekly_data_entry_params
    params.require(:weekly_data_entry).permit(:goal_id, :business_id, :user_id, :contacted_leads, :paid_customers, :budget_expences, :revenue, :conversion_rate, :date)
  end
end

app/helpers/weekly_data_entries_helper.rb
module WeeklyDataEntriesHelper
end

app/views/weekly_data_entries/_form.html.erb
<%= form_with(model: weekly_data_entry) do |form| %>
  <% if weekly_data_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weekly_data_entry.errors.count, "error") %> prohibited this data entry from being saved:</h2>
      <ul>
        <% weekly_data_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <%= form.label :date %>
      <%= form.date_field :date, class: "form-control", required: true %>
    </div>
  </div>
  <div>
    <h5 class="heading-fonts my-3 text-center">Product Leads Per Week</h5>
    <div class="row">
      <% @goal.business.products.each do |product| %>
        <% if @goal.products.split("-#-").map(&:strip).include?(product.name) %>
          <div class="col-md-4" id="channel-leads-per-week">
            <%= form.label product.name %>
            <% if weekly_data_entry.persisted? %>
              <%= number_field_tag "#{product.name}", weekly_data_entry.product_leads_hash[product.name] %>
            <% else %>
              <%= number_field_tag "#{product.name}" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div>
    <h5 class="heading-fonts my-3 text-center">Channel Leads Per Week</h5>
    <div class="row">
      <% @goal.business.channels.each do |channel| %>
        <% if @goal.channels.split("-#-").map(&:strip).include?(channel.name) %>
          <div class="col-md-4" id="channel-leads-per-week">
            <%= form.label channel.name %>
            <% if weekly_data_entry.persisted? %>
              <%= number_field_tag "#{channel.name}", weekly_data_entry.channel_leads_hash[channel.name] %>
            <% else %>
              <%= number_field_tag "#{channel.name}" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= form.label :contacted_leads %>
      <%= form.number_field :contacted_leads, class: "form-control", required: true %>
    </div>
    <div class="col-md-6">
      <%= form.label :paid_customers %>
      <%= form.number_field :paid_customers, class: "form-control", required: true %>
    </div>
    <div class="col-md-6">
      <%= form.label "Budget expenses" %>
      <%= form.number_field :budget_expences, class: "form-control", required: true %>
    </div>
    <div class="col-md-6">
      <%= form.label :revenue %>
      <%= form.number_field :revenue, class: "form-control", required: true %>
    </div>
    <div class="col-md-2 my-3">
      <%= form.submit action_text(weekly_data_entry), class: "btn btn-success" %>
    </div>
    <%= form.hidden_field :business_id, value: @goal.business_id%>
    <%= form.hidden_field :user_id, value: current_user.id%>
    <%= form.hidden_field :goal_id, value: @goal.id %>
  </div>
<% end %>

app/views/weekly_data_entries/_modal.html.erb
<!-- Button trigger modal -->
<% if weekly_data_entry.persisted? %>
  <button type="button" class="edit-link-yellow" data-bs-toggle="modal" data-bs-target="#weeklyDataEntry-<%= id_suffix %>">
    <i class="bi bi-pencil-square"></i>
  </button>
<% else %>
  <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#weeklyDataEntry-<%= id_suffix %>">
    <%= action_text(weekly_data_entry) + " Weekly Entry" %>
  </button>
  <% end %>
<!-- Modal -->
<div class="modal fade" id="weeklyDataEntry-<%= id_suffix %>" tabindex="-1" aria-labelledby="weeklyDataEntryLabel-<%= id_suffix %>" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <%= render partial: "weekly_data_entries/form", locals: { weekly_data_entry: weekly_data_entry } %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/weekly_data_entries/_weekly_data_entry.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold" style="color: black;">Weekly Input</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Week</th>
            <th>Total Leads</th>
            <th>Channel Leads</th>
            <th>Contacted Leads</th>
            <th>Paid Customers</th>
            <th>Conversion Rate</th>
            <th>Budget Expense</th>
            <th>Revenue</th>
            <th>Products/Service</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @goal.weekly_data_entries.each do |data| %>
            <tr>
              <th><%= data.date.strftime("%-V") %></th>
              <td><%= data.leads_per_week %></td>
              <td>
                <% data.channel_leads_array_of_hashes.each do |hash| %>
                  <p><%= hash.keys.first %> : <%= hash.values.first %></p>
                <% end %>
              </td>
              <td><%= data.contacted_leads %> </td>
              <td><%= data.paid_customers %></td>
              <td><%= data.conversion_rate.round(2) %> %</td>
              <td>$ <%= data.budget_expences %></td>
              <td>$ <%= data.revenue %></td>
              <td>
                <% data.product_leads_array_of_hashes.each do |hash| %>
                  <p><%= hash.keys.first %> : <%= hash.values.first %></p>
                <% end %>
              </td>
              <td class="d-flex justify-content-between">
                <%= render partial: "weekly_data_entries/modal", locals: { weekly_data_entry: data, id_suffix: data.id }%>
                <%= link_to weekly_data_entry_path(data), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "general-delete-link" do %>
                  <i class="bi bi-x-circle"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/weekly_data_entries/form_error_page.html.erb
<div class="container-fluid bg-light" style="height: 100vh;">
  <div class="py-5">
    <%= link_to goal_path(@goal) do %>
    <%= render "shared/buttons/back-icon"%>
  <% end %>
  </div>
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= render partial: "weekly_data_entries/form", locals: { weekly_data_entry: @weekly_data_entry, btn_text: "update" } %>
    </div>
  </div>
</div>