config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :businesses do
    member do
      get :table_statistics
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :channels
  resources :goals do 
    member do
      get :scoreboard_summary
    end

    collection do
      get :form_error_page
    end
  end
  resources :products
  resources :weekly_data_entries do
    collection do
      get :form_error_page
    end
  end
end

app/views/layouts/_dashboard_navbar.html.erb
<nav class="navbar navbar-expand navbar-light topbar mb-4 static-top shadow" style="background-color: #0b513b; padding-right: 50px;">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="bi bi-list"></i>
  </button>
  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>
    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <div class="dropdown">
        <a class="dropdown-toggle text-white" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          <span><%= current_user.first_name %></span>
          <img style="width: 40px;" class="sidebar-card-illustration mx-2" src="/assets/undraw_profile-9bafc822646b3bd68527e91e2d74d980658945d7207091d77c13cf2ff2a8ef4c.svg">
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li> 
            <% if current_user.present? %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "transparent-btn" %>
            <% end %>
          </li>
        </ul>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <li class="text-white p-2" style="border-bottom: 2px solid white;">
    <span class="sidebar-brand-icon">
      <i class="bi bi-emoji-smile-fill" style="font-size: 2em;"></i>
    </span>
    <span class="sidebar-brand-text p-1 d-none d-md-inline score-borad-tag">Scoreboard</span>
  </li>
  <% if current_user.businesses.present? && current_user.businesses.first.goals.present? %>
    <li class="side-bar-lists pt-5">
      <%= link_to scoreboard_summary_goal_path(current_user.businesses.first.goals.last), class: "sidebar-brand d-flex align-items-center justify-content-between" do %>
        <div class="sidebar-brand-icon">
          <i class="bi bi-speedometer"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Dashboard</div>
      <% end %>
    </li>
  <% end %>
  <% if current_user.businesses.present? %>
    <li class="side-bar-lists">
      <%= link_to business_path(current_user.businesses.first), class: "sidebar-brand d-flex align-items-center justify-content-between" do %>
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="bi bi-briefcase-fill"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Business Goals</div>
      <% end %>
    </li>
    <li class="side-bar-lists">
      <%= link_to table_statistics_business_path(current_user.businesses.first), class: "sidebar-brand d-flex align-items-center justify-content-between" do %>
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="bi bi-table"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Goal Stats</div>
      <% end %>
    </li>
  <% end %>
  <!-- Divider -->
  <div class="sidebar-card d-none d-lg-flex my-5">
    <%= image_tag("undraw_profile.svg", class: "sidebar-card-illustration mb-2") %>
    <p class="text-center mb-2">
      <strong>Client Scoreboard Customer Support</strong> is
      availale for user onboarding or any other issue you
      might have.
    </p>
    <a class="btn btn-success btn-sm" href="mailto:support@clientscorboards.com">Contact Us</a>
  </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusinessLeadAnalytics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Display:ital,wght@1,200&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <%= render "shared/flash_notification" %>
    <%= yield %>
   
  </body>
</html>

app/views/layouts/dashboard_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusinessLeadAnalytics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Display:ital,wght@1,200&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="wrapper">
      <!-- Sidebar -->
      <%= render "layouts/sidebar" %>
      <!-- End of Sidebar -->
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <%= render "layouts/dashboard_navbar" %>
          <%= render "shared/flash_notification" %>
          <!-- End of Topbar -->
          <!-- Begin Page Content -->
          <%= yield %>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Client Scoreboard <%= Time.now.year %></span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
  </body>
</html>